version: '2.4'
 
services:
  mnist_api:
    build: ./mnist_api
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "5000:5000"
    volumes:
      - "./mnist_api:/projects"
      - "./images:/projects/images"
      - "./logs/mnist:/projects/logs"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: /bin/sh -c "tail -f /dev/null"
    command: flask run --host 0.0.0.0 --port 5000

  mnist2_api:
    build: ./mnist2_api
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "5001:5001"
    volumes:
      - "./mnist2_api:/projects"
      - "./images:/projects/images"
      - "./logs/mnist2:/projects/logs"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: /bin/sh -c "tail -f /dev/null"
    command: flask run --host 0.0.0.0 --port 5001